services:
  - type: web
    name: skeen-eggs
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 24